language: python

python:
- 2.7

before_script:
- pip install -r requirements.txt
- pip install -r requirements_test.txt

script:
- make test
- make bandit

after_success:
- coveralls
- coverage xml
- python-codacy-coverage -r coverage.xml
