# Python CircleCI 2.0 configuration file
python: &python
  docker:
    - image: circleci/python:3.6

version: 2

jobs:
  build:
    <<: *python
    steps:
      - checkout
      - run:
          name: Install/Update python-dev
          command: sudo apt-get update && sudo apt-get install -y python-dev
      - run:
          name: Update PATH
          command: echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install tox
          command: pip install --user $(cat requirements_test.txt | grep tox)
      - run:
          name: Create coverage dir
          command: mkdir test-reports
      - run:
          name: Run tests
          command: TOXBUILD=true tox
      - store_artifacts:
          path: test-reports/
      - store_test_results:
          path: test-reports/

  deploy:
    <<: *python
    steps:
      - checkout
      - run:
          name: Update PATH
          command: echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install Twine
          command: pip install --user twine
      - run:
          name: Push to cheeseshop
          command: ./push_to_cheeseshop.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^\d+(?:\.\d+){2}$/
            branches:
              only: master